// Java 25+
// Feature shown: records, final in Java 16+
package chapter01;

import java.util.logging.Logger;

/**
 * Listing 1.4 — ProductRecord.java
 * Demonstrates: records with compact canonical constructor validation,
 * and auto-generated accessors, equals, hashCode, and toString.
 * Chapter 1: Modern Java: A Shift in Mindset
 * Requires: Java 25+ (compiled with --enable-preview --release 21 for
 * the void main() instance main method)
 */

// A record declaration: compiler generates constructor, accessors, equals, hashCode, toString
public record ProductRecord(
        String id, String name, double price, String category) {

    // Compact canonical constructor for validation — no boilerplate required
    public ProductRecord {
        if (price < 0) {
            throw new IllegalArgumentException("Price cannot be negative");
        }
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Name required");
        }
    }
}

// Records have no no-arg constructor, so an instance void main() cannot
// serve as the launch entry point inside ProductRecord itself — this small
// sibling class hosts the demo entry point and Logger instead.
class ProductRecordDemo {

    private static final Logger log =
            Logger.getLogger(ProductRecordDemo.class.getName());

    void main() {
        var product = new ProductRecord(
                "P-001", "Wireless Keyboard", 49.99, "Electronics"); // create record instance
        log.info(String.valueOf(product));          // toString auto-generated by compiler
        log.info("Name : " + product.name());      // accessor auto-generated by compiler
        log.info("Price: " + product.price());     // accessor auto-generated by compiler
    }
    // Output:
    // ProductRecord[id=P-001, name=Wireless Keyboard, price=49.99, category=Electronics]
    // Name : Wireless Keyboard
    // Price: 49.99
}